export const EDIT_COURSE_UPDATE_TYPE: string = 'EDIT_COURSE_UPDATE_TYPE';
export const EDIT_COURSE_CANCEL_TYPE: string = 'EDIT_COURSE_CANCEL_TYPE';
export const PLAYLIST_PLAY_PREVIOUS: string = 'PLAYLIST_PLAY_PREVIOUS';
export const PLAYLIST_PLAY_NEXT: string = 'PLAYLIST_PLAY_NEXT';
